include:
  - board: nice_nano_v2
    shield: clog_left
  - board: nice_nano_v2
    shield: clog_right
  - board: seeeduino_xiao_ble
    shield: clog_v2_left
  - board: seeeduino_xiao_ble
    shield: clog_v2_right
  - board: nice_nano_v2
    shield: osprette
  - board: adafruit_kb2040
    shield: osprette
